// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv6vef3c70Y-7m1LjlAMJP7jJBb8yhuwc',
    appId: '1:395943878778:web:fdd08bc09515342c365bc3',
    messagingSenderId: '395943878778',
    projectId: 'healthcare-3a512',
    authDomain: 'healthcare-3a512.firebaseapp.com',
    storageBucket: 'healthcare-3a512.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaaL4IyDTEt6OuljQpFZkCpof4J7_C1Xw',
    appId: '1:395943878778:android:9dc2a595e9dc4051365bc3',
    messagingSenderId: '395943878778',
    projectId: 'healthcare-3a512',
    storageBucket: 'healthcare-3a512.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4EA6NY-nl7mNlWZ-3zr95p-Z-oKHR2tw',
    appId: '1:395943878778:ios:509151231f96b018365bc3',
    messagingSenderId: '395943878778',
    projectId: 'healthcare-3a512',
    storageBucket: 'healthcare-3a512.appspot.com',
    iosBundleId: 'com.example.healthCare',
  );
}
